import Menu from "@/components/Menu";
import Nav from "@/components/Nav";
import "@/styles/globals.css";

export const metadata = {
	title: "MovieCine",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en" suppressHydrationWarning={true}>
			<body
				className="font-roboto min-h-screen text-white bg-mainBlack"
				suppressHydrationWarning={true}>
				<div className="flex">
					<Menu></Menu>
					<main className="w-full">
						<Nav></Nav>
						{children}
					</main>
				</div>
			</body>
		</html>
	);
}
