import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster";
import { WatchlistProvider } from "@/context/watchlistContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Moviecine",
	description: "Generated by create next app",
	icons: {
		icon: "/icons/logo.svg",
	},
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${inter.className} bg-mainBlack-1 main_custom_scrollbar`}>
				<WatchlistProvider>{children}</WatchlistProvider>
				<Toaster />
			</body>
		</html>
	);
}
